name: Continuous Integration
on: pull_request_target

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install dependencies and Build the project
        run: mvn clean install
      - name: Upload code coverage report to workflow as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: core/target/site
          path: coverage
      - name: Upload code coverage report to codecov.io and comment in pull request
        uses: codecov/codecov-action@v1
      - name: Upload Sonar report to sonarcloud.io and comment in pull request
        run: mvn -B verify sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths=../core/target/site/jacoco/jacoco.xml -Dsonar.organization=adobeinc -Dsonar.projectKey=adobe_aem-spa-project-core -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
